[2024-07-19T18:34:05.358+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.load_data manual__2024-07-19T18:33:57.359929+00:00 [queued]>
[2024-07-19T18:34:05.370+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.load_data manual__2024-07-19T18:33:57.359929+00:00 [queued]>
[2024-07-19T18:34:05.372+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-19T18:34:05.392+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2024-07-19 18:33:57.359929+00:00
[2024-07-19T18:34:05.402+0000] {standard_task_runner.py:60} INFO - Started process 720 to run task
[2024-07-19T18:34:05.405+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_pipeline', 'load_data', 'manual__2024-07-19T18:33:57.359929+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/crypto_pipeline_dag.py', '--cfg-path', '/tmp/tmpaah1d372']
[2024-07-19T18:34:05.408+0000] {standard_task_runner.py:88} INFO - Job 325: Subtask load_data
[2024-07-19T18:34:05.469+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_pipeline.load_data manual__2024-07-19T18:33:57.359929+00:00 [running]> on host 58dd90220664
[2024-07-19T18:34:05.540+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T18:33:57.359929+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T18:33:57.359929+00:00'
[2024-07-19T18:34:05.551+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_pipeline_dag.py", line 66, in load_data_with_xcom
    load_data(data)
TypeError: load_data() missing 14 required positional arguments: 'btcusdt_rate', 'ethusdt_rate', 'solusdt_rate', 'btcbrl_rate', 'ethbrl_rate', 'solbrl_rate', 'btcusdt_total', 'ethusdt_total', 'solusdt_total', 'btcbrl_total', 'ethbrl_total', 'solbrl_total', 'brl_total', and 'usdt_total'
[2024-07-19T18:34:05.561+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=crypto_pipeline, task_id=load_data, execution_date=20240719T183357, start_date=20240719T183405, end_date=20240719T183405
[2024-07-19T18:34:05.572+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 325 for task load_data (load_data() missing 14 required positional arguments: 'btcusdt_rate', 'ethusdt_rate', 'solusdt_rate', 'btcbrl_rate', 'ethbrl_rate', 'solbrl_rate', 'btcusdt_total', 'ethusdt_total', 'solusdt_total', 'btcbrl_total', 'ethbrl_total', 'solbrl_total', 'brl_total', and 'usdt_total'; 720)
[2024-07-19T18:34:05.619+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T18:34:05.634+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
