[2024-07-22T13:00:01.381+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.fetch_data scheduled__2024-07-22T12:55:00+00:00 [queued]>
[2024-07-22T13:00:01.387+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.fetch_data scheduled__2024-07-22T12:55:00+00:00 [queued]>
[2024-07-22T13:00:01.388+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-22T13:00:01.400+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-07-22 12:55:00+00:00
[2024-07-22T13:00:01.405+0000] {standard_task_runner.py:60} INFO - Started process 6432 to run task
[2024-07-22T13:00:01.407+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_pipeline', 'fetch_data', 'scheduled__2024-07-22T12:55:00+00:00', '--job-id', '553', '--raw', '--subdir', 'DAGS_FOLDER/crypto_pipeline_dag.py', '--cfg-path', '/tmp/tmpguhr8i8i']
[2024-07-22T13:00:01.408+0000] {standard_task_runner.py:88} INFO - Job 553: Subtask fetch_data
[2024-07-22T13:00:01.446+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_pipeline.fetch_data scheduled__2024-07-22T12:55:00+00:00 [running]> on host 58dd90220664
[2024-07-22T13:00:01.505+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T12:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-22T12:55:00+00:00'
[2024-07-22T13:00:01.895+0000] {logging_mixin.py:188} INFO - Error: 400
[2024-07-22T13:00:01.898+0000] {logging_mixin.py:188} INFO - {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
[2024-07-22T13:00:01.903+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_pipeline_dag.py", line 28, in fetch_data_with_xcom
    df = fetch_data()
  File "/opt/airflow/Program.py", line 11, in fetch_data
    return generate_dataframe(api_key, signature_key)
  File "/opt/airflow/src/generate_data_frame.py", line 28, in generate_dataframe
    for currency, amount in crypto_amounts.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2024-07-22T13:00:01.915+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=crypto_pipeline, task_id=fetch_data, execution_date=20240722T125500, start_date=20240722T130001, end_date=20240722T130001
[2024-07-22T13:00:01.927+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 553 for task fetch_data ('NoneType' object has no attribute 'items'; 6432)
[2024-07-22T13:00:01.943+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-22T13:00:01.959+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
